#!/bin/bash

# make files executable
chmod +x /usr/bin/sci-bat-example-webserver
chmod +x /usr/bin/sci-bat-example-modbus
chmod +x /usr/bin/sci-bat-example-mqtt

# generate a temporary ssl certificate
openssl req -x509 -newkey rsa:2048 -keyout /etc/sci-bat-example-webserver/key.pem -out /etc/sci-bat-example-webserver/cert.pem -sha256 -days 365 -nodes -subj /CN=localhost

# Allow port access
setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/sci-bat-example-webserver

# Allow all users to read from the configuration and application data
chmod -R 775 /etc/sci-bat-example-webserver/
chmod -R 775 /usr/bin/sci-bat-example-webserver.d/

# enable service
systemctl enable sci-bat-example-webserver.service
systemctl start sci-bat-example-webserver.service
